version: '3'

services:
  data:
    image: postgres:11.1-alpine
    container_name: eventmng_postgre
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'mydb'
      POSTGRES_USER: 'bkteam'
      POSTGRES_PASSWORD: 'Abcd1234'
    restart: always
    volumes:
      - ./db_initial.sql:/docker-entrypoint-initdb.d/db_initial.sql